### PR TITLE
Created a Music Visualizer

### PR DESCRIPTION
**Pull request by JuanitaCathy**
Created a PR that closes the issue #57 Music Visualization

### CODE REVIEW

**Review by harshal255 — APPROVED** [review]

**Comment by harshal255** [comment]
> Created a PR that closes the issue #57 Music Visualization

image
 what is this dude??

**Comment by harshal255** [comment]
> You upload an audio file using the browse button and only then u can see the visuals Try uploading an audio file, you'll be able to see visuals inside the box

Okay I will check but first you should add good style😅👍

**Comment by JuanitaCathy** [comment]
> > You upload an audio file using the browse button and only then u can see the visuals Try uploading an audio file, you'll be able to see visuals inside the box
> 
> Okay I will check but first you should add good style😅👍

Okayy i was focusing on the backend and ignored the style :(
I'll add some CSS to it

**Comment by harshal255** [comment]
> > > You upload an audio file using the browse button and only then u can see the visuals Try uploading an audio file, you'll be able to see visuals inside the box
> > 
> > 
> > Okay I will check but first you should add good style😅👍
> 
> Okayy i was focusing on the backend and ignored the style :( I'll add some CSS to it

Yeahh

**Comment by JuanitaCathy** [comment]
@harshal255 i added some style to it

**Pull request merged**
