### PR TITLE
Added Random Quote Generator

### PR DESCRIPTION
**Pull request by PrathameshTheurkar**
Added Random Quote Generator website using HTML , CSS , Js under #4

### CODE REVIEW

**Review by harshal255 — APPROVED** [review]

**Comment by harshal255** [comment]
> Added Random Quote Generator website using HTML , CSS , Js under #4

Amazing work brother, I appreciate your dedication & work..🫡🫡🚀🚀

**Comment by PrathameshTheurkar** [comment]
Thanks for merging my PR , is this merged PR valid for hacktoberfest ??

**Comment by harshal255** [comment]
> Thanks for merging my PR , is this merged PR valid for hacktoberfest ??

Yeah I merged & add label for hacktober
## are you getting a waiting pr label on hacktoberfest portal??

like 
image

**Comment by PrathameshTheurkar** [comment]
yeah I am getting this label , Thank you very much.

**Comment by harshal255** [comment]
🥂🥳

Harshal Kahar
On 9 Oct 2023, 8:32 PM +0530, Theurkar Prathamesh Ravindra ***@***.***>, wrote:

yeah I am getting this label , Thank you very much.

**Pull request merged**
