### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by aparna03dubey**
Improved UI of the temperature converter app.

### CODE REVIEW

**Comment by aparna03dubey** [comment]
@harshal255 Please review the changes.

**Comment by aparna03dubey** [comment]
@harshal255 Please see if the changes made are as the ones suggested by you.

**Review by harshal255 — APPROVED** [review]

**Comment by harshal255** [comment]
> @harshal255 Please see if the changes made are as the ones suggested by you.

Okay bro great work
could you add media query as well for responsive??

**Comment by aparna03dubey** [comment]
Fine..

**Comment by harshal255** [comment]
> Please add the hacktoberfest tag

Yeahh

**Pull request merged**
