### PR TITLE
Added Search Bar #89

### LINKED ISSUE #89: Make a Search bar with good style to search project using topic name or project name
use es6+ filter method

### PR DESCRIPTION
**Pull request by AryanBakliwal**
### Added Search Bar

Added a search bar to search projects using topic name.
The pagination buttons also update accordingly.

closes #89

### CODE REVIEW

**Review by harshal255 — APPROVED** [review]

**Comment by harshal255** [comment]
> ### Added Search Bar
> 
> Added a search bar to search projects using topic name. The pagination buttons also update accordingly.
> 
> closes #89

Hello brother 
sorry but can you implement this functionality again??
image
I can't solve conflict files because a lot of changes because I first merge pr of adding 3 filter button (all, project & games)

**Comment by harshal255** [comment]
> ### Added Search Bar
> 
> Added a search bar to search projects using topic name. The pagination buttons also update accordingly.
> 
> closes #89

pls first take pull & then implement if you want..

**Comment by AryanBakliwal** [comment]
Yes @harshal255, I'll do it right away

**Comment by harshal255** [comment]
> Yes @harshal255, I'll do it right away

Okay thanks a lot bro
& sorry for that

**Pull request closed without merging**
