### PR TITLE
Fix issue #83  (project doesn't open on page 2 and 3))

### PR DESCRIPTION
**Pull request by AbdullahTheDev**
Fixed - Project doesn't opened on page 2 & page 3 #83

### CODE REVIEW

**Review by harshal255 — APPROVED** [review]

**Comment by harshal255** [comment]
> Fixed - Project doesn't opened on page 2 & page 3 #83

Thanks a lot brother✨🐍

**Comment by harshal255** [comment]
> Fixed - Project doesn't opened on page 2 & page 3 #83

Hello brother
can you fix again this issue?
after taking pull, now project link doesn't opened on every pages

**Comment by AbdullahTheDev** [comment]
> > Fixed - Project doesn't opened on page 2 & page 3 #83
> 
> Hello brother
> can you fix again this issue?
> after taking pull, now project link doesn't opened on every pages

Ok I'll fix it again.

**Comment by harshal255** [comment]
> > Fixed - Project doesn't opened on page 2 & page 3 #83
> 
> Hello brother can you fix again this issue? after taking pull, now project link doesn't opened on every pages

Okay wait when I merge search functionality & then you should working on it..✨
I'll inform you when I merge that functionality to prevention of conflict files👍

**Comment by harshal255** [comment]
> > > Fixed - Project doesn't opened on page 2 & page 3 #83
> > 
> > 
> > Hello brother
> > can you fix again this issue?
> > after taking pull, now project link doesn't opened on every pages
> 
> Ok I'll fix it again.

Hello bro. now you can fix that issue
you should take pull of the stream repository💪🏻

**Comment by AbdullahTheDev** [comment]
> > > > Fixed - Project doesn't opened on page 2 & page 3 #83
> > > 
> > > 
> > > Hello brother
> > > can you fix again this issue?
> > > after taking pull, now project link doesn't opened on every pages
> > 
> > Ok I'll fix it again.
> 
> Hello bro. now you can fix that issue
> you should take pull of the stream repository💪🏻

Okay, I will fix it as soon I an free

**Pull request merged**
